<node TEXT="$$$NODE$$$" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ID="ID_$$$TAG$$$" CREATED="1610875898933" MODIFIED="1610875929523" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#ff0000" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<richcontent TYPE="DETAILS" HIDDEN="true">

$$$TEXT$$$
  
</richcontent>
