<?xml version="1.0" encoding="UTF-8"?><map version="freeplane 1.8.0">
<!--To view this file, download free mind mapping software Freeplane from http://freeplane.sourceforge.net -->
<node LOCALIZED_TEXT="new_mindmap" COLOR="#000000" STYLE="oval" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" FOLDED="false" ID="ID_1283834136" CREATED="1610875858625" MODIFIED="1610875858625" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="18" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<hook NAME="MapStyle">
    <properties fit_to_viewport="false" edgeColorConfiguration="#808080ff,#ff0000ff,#0000ffff,#00ff00ff,#ff00ffff,#00ffffff,#7c0000ff,#00007cff,#007c00ff,#7c007cff,#007c7cff,#7c7c00ff"/>

<map_styles>
<stylenode LOCALIZED_TEXT="styles.root_node" COLOR="#000000" STYLE="oval" UNIFORM_SHAPE="true" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt" VGAP_QUANTITY="24.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="24" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<stylenode LOCALIZED_TEXT="styles.predefined" COLOR="#000000" STYLE="bubble" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" POSITION="right" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<stylenode LOCALIZED_TEXT="default" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.details" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.attributes" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="9" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.note" COLOR="#000000" BACKGROUND_COLOR="#ffffff" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="LEFT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="defaultstyle.floating" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="hide_edge" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<cloud COLOR="#f0f0f0" SHAPE="ROUND_RECT"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.user-defined" COLOR="#000000" STYLE="bubble" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" POSITION="right" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<stylenode LOCALIZED_TEXT="styles.topic" COLOR="#18898b" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="Liberation Sans" SIZE="10" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subtopic" COLOR="#cc3300" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="Liberation Sans" SIZE="10" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.subsubtopic" COLOR="#669900" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="Liberation Sans" SIZE="10" BOLD="true" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.important" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<icon BUILTIN="yes" src="yes.svg" height="16"/>
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
</stylenode>
<stylenode LOCALIZED_TEXT="styles.AutomaticLayout" COLOR="#000000" STYLE="bubble" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" POSITION="right" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level.root" COLOR="#000000" STYLE="oval" SHAPE_HORIZONTAL_MARGIN="13" SHAPE_HORIZONTAL_MARGIN_QUANTITY="10.0 pt" SHAPE_VERTICAL_MARGIN="13" SHAPE_VERTICAL_MARGIN_QUANTITY="10.0 pt" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="18" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,1" COLOR="#0033ff" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="16" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,2" COLOR="#00b439" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="14" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,3" COLOR="#990000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="12" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,4" COLOR="#111111" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,5" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,6" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,7" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,8" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,9" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,10" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
<stylenode LOCALIZED_TEXT="AutomaticLayout.level,11" COLOR="#000000" STYLE="fork" NUMBERED="false" FORMAT="STANDARD_FORMAT" TEXT_ALIGN="DEFAULT" MAX_WIDTH="378" MAX_WIDTH_QUANTITY="10.0 cm" MIN_WIDTH="0" MIN_WIDTH_QUANTITY="0.0 cm" BORDER_WIDTH_LIKE_EDGE="false" BORDER_WIDTH="1.0 px" BORDER_COLOR_LIKE_EDGE="true" BORDER_COLOR="#808080" BORDER_DASH_LIKE_EDGE="false" BORDER_DASH="SOLID" ICON_SIZE="12.0 pt">
<edge STYLE="bezier" COLOR="#808080" WIDTH="thin" DASH="SOLID"/>
<font NAME="SansSerif" SIZE="10" BOLD="false" STRIKETHROUGH="false" ITALIC="false"/>
</stylenode>
</stylenode>
</stylenode>
</map_styles>
</hook>
<hook NAME="AutomaticEdgeColor" COUNTER="3" RULE="ON_BRANCH_CREATION"/>
